homebrew_packages:
  # init
  - name: ansible
  - name: python
  - name: python3
  - name: mas
  # Shell
  - name: yash
  # GNU
  - name: gawk
  - name: gnu-sed
  - name: coreutils
  - name: findutils
  - name: grep
  # Git
  - name: git
  - name: ghq
  - name: gh
  # Terminal
  - name: peco
  - name: tokei
  - name: jq
  - name: yq
  - name: pwgen
  - name: moreutils
  - name: nkf
  - name: mcat
  # Alternate CLI
  - name: eza
  - name: bat
  - name: ripgrep
  # Media
  - name: yt-dlp
  - name: ffmpeg
  - name: zopfli
  - name: webp
  - name: exiftool
  - name: pngquant
  # Editor
  - name: neovim
  # Develop
  - name: nim
  - name: dotnet
  - name: cmake
  - name: nodebrew
  - name: direnv
  # Web
  - name: ddgr
  - name: scraps
  - name: cloudflared
  # curl
  - name: openssl
  - name: curl
    option: with-openssl
