homebrew_cask_packages:
  # Web
  - name: brave-browser
  - name: discord
  - name: transmission
  # Virtual sound device
  - name: blackhole-2ch
  - name: blackhole-16ch
  # System
  - name: scroll-reverser
  - name: appcleaner
  - name: the-unarchiver
  - name: powershell
  - name: raycast
  - name: wezterm
  # Editor
  - name: visual-studio-code
  - name: godot
  # Media
  - name: iina
  - name: krita
  - name: obs
